# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

r: release
latex: false
pandoc: false

env:
 global:
   - CRAN: http://cran.rstudio.com

sudo: false
cache:
  apt: true
  packages: true

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'

notifications:
  email: false
